name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi
